### PR TITLE
patchforreview_remover.py: Support both Gerrit and Gitlab

### PR DESCRIPTION
**Pull request by dancysoft**

### CODE REVIEW

**Comment by brennen** [comment]
On a read-through, this looks sensible.

I am wondering if we're going to want to have a gitlabbot user, rather than, gerritbot _adding_ the tag?  That does complicate things, but it's come up a couple of times already.

(I guess ideally maybe "gerritbot" would just become "CodeReviewBot" or something.)

**Comment by dancysoft** [comment]
> (I guess ideally maybe "gerritbot" would just become "CodeReviewBot" or something.)

I was just thinking the same thing. That may simplify things for the future versions of ourselves.

**Comment by brennen** [comment]
https://codesearch.wmcloud.org/search/?q=gerritbot

Seems like there wouldn't be a lot to change _in code_, at least. On the other hand, I guess I can imagine workflows keying off the name somewhere.

**Review by Ladsgroup — APPROVED** [review]
Thank you so much for doing this.

**Comment by dancysoft** [comment]
@Ladsgroup Can you confirm that this has been deployed?

**Comment by Ladsgroup** [comment]
It's pulled toolforge, might be the container not getting updated. Isn't it working?

**Comment by dancysoft** [comment]
> It's pulled toolforge, might be the container not getting updated. Isn't it working?

I didn't try testing yet.  Didn't want to bother if it hadn't been deployed yet.   Sounds like it's ready to test now.  Thanks.

**Pull request merged**
