### PR TITLE
Replace deploy1001 with deployment host

### PR DESCRIPTION
**Pull request by ZabeMath**
deploy1001 was decommissioned and was replace with deploy1002

### CODE REVIEW

**Comment by jdforrester** [comment]
Maybe change to the `deployment.eqiad.wmnet` pointer instead?

**Comment by Ladsgroup** [comment]
> Maybe change to the `deployment.eqiad.wmnet` pointer instead?

I personally don't like it because with every change, it gives me the scary "host fingerprtint has changed" and I have to check the fingerprint, etc. which is for me is much easier to just remember to use the other node (and if I fail, it has this massive motd reminding me not to use it)

That being said, It's just a personal preference to me and I wouldn't block the change.

**Comment by urbanecm** [comment]
Maybe "deployment host", to refer to host by its role and not hostname?

**Comment by Ladsgroup** [comment]
> Maybe "deployment host", to refer to host by its role and not hostname?

SGTM

**Comment by ZabeMath** [comment]
> > Maybe "deployment host", to refer to host by its role and not hostname?
> 
> SGTM

Then let's do that.

**Review by urbanecm — APPROVED** [review]

**Pull request merged**
