### PR TITLE
new_wikis_handler: Inform CVN

### LINKED ISSUE #19: Ping CVN folks to setup IRC monitoring
Another post-creation operation: ping [CVN](https://meta.wikimedia.org/wiki/Countervandalism_Network) folks to setup IRC monitoring of the newly-created wiki to watch for vandalism/spam. Patch will shortly follow.

### PR DESCRIPTION
**Pull request by MarcoAurelioWM**
Fixes #19.

### CODE REVIEW

**Comment by MarcoAurelioWM** [comment]
I'd like to hear from @krinkle, which is a CVN staffer; because another place might be more appropriate to request this.

**Comment by MarcoAurelioWM** [comment]
Well, I guess we can change the link at a later date :-)

**Comment by Krinkle** [comment]
Requests for new bots and new wikis typically go to <https://github.com/countervandalism/infrastructure>.

However, assuming new wikis are small by default, this is more a question for SWMT and less about CVN.

I do not know how the operators of `#cvn-sw` prefer to be interacted with. I checked [m:SWMT](https://meta.wikimedia.org/wiki/Small_Wiki_Monitoring_Team) and [m:SWMT/IRC](https://meta.wikimedia.org/wiki/Small_Wiki_Monitoring_Team/IRC) but found nothing about who or where to contact the local operators.

**Comment by MarcoAurelioWM** [comment]
I've been adding new wikis to the bots for the last year or so, and keep
that talk page in my watchlist. For now I think it's a good place to let
#cvn-sw operators know that a new wiki needs to be added, unless you think
another place is better of course. Thanks.

**Pull request merged**
